version: '3'
services:
  web:
      build: .
      # command: python -u app.py
      ports:
          - "9876:9876"
      volumes:
          - .:/app
      links:
          - mongo
  mongo:
      image: mongo